# Used on master and staging branches
name: Development CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - '*' # Push events on all branchs
      - '*/*'
      - '!master' # Exclude master
      - '!next' # Exclude next
      - '!alpha' # Exclude alpha
      - '!beta' # Exclude beta

jobs:
  test:
    name: Test, Build & Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14']

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Tests
        run: yarn test:lint

      - name: Build
        run: yarn build
